const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
vm.runInThisContext(fs.readFileSync('gymbromatics/calibration.js','utf8'));
const points={ear:[100,30],shoulder:[100,60],hip:[100,160],knee:[100,250],ankle:[100,340],heel:[95,350],toe:[130,350]};
const frames=Array.from({length:30},()=>({calibration_points:{left:structuredClone(points),right:null}}));
const estimate=BodyCalibration.estimate(frames,10,30,'left');
assert.equal(estimate.available,true);assert.equal(estimate.validFrames,7);
assert.deepEqual(estimate.segments,{foot:10,shank:90,thigh:90,torso:100,neck:30});
const scale=BodyCalibration.scale(180,estimate.segments,6);
assert.equal(scale.totalPixels,339.2);assert.equal(scale.cmPerPixel,180/339.2);
assert.equal(BodyCalibration.scale(180,estimate.segments,0).totalPixels,320);
assert.equal(BodyCalibration.scale(0,estimate.segments),null);
assert.equal(BodyCalibration.scale(180,{...estimate.segments,neck:null}),null);
assert.equal(BodyCalibration.scale(180,estimate.segments,21),null);
assert.equal(BodyCalibration.estimate(frames,10,30,'right').available,false);
assert.equal(BodyCalibration.estimate(frames,null,30,'left').available,false);
const missing=structuredClone(frames);for(let i=7;i<=13;i++)missing[i].calibration_points.left.ear=null;
assert.equal(BodyCalibration.estimate(missing,10,30,'left').available,false);
const crouched=structuredClone(frames);for(const f of crouched)f.calibration_points.left.hip=[20,240];
assert.equal(BodyCalibration.estimate(crouched,10,30,'left').available,false);
const mirrored=frames.map(f=>({calibration_points:{left:Object.fromEntries(Object.entries(f.calibration_points.left).map(([k,p])=>[k,[1000-2*p[0],2*p[1]]]))}}));
assert.equal(BodyCalibration.scale(180,BodyCalibration.estimate(mirrored,10,30,'left').segments).cmPerPixel,scale.cmPerPixel/2);
console.log('Segment calibration: exact sum, scale invariance, missing data, posture and corrections passed');
