(() => {
  'use strict';
  const MAX_BYTES=250*1024*1024, TYPES={mp4:'video/mp4',mov:'video/quicktime',webm:'video/webm'};
  const ORDER=['created','uploaded','queued','processing','complete'];
  const STATUS={created:'הסשן נוצר. מעלים את הסרטון…',uploaded:'הסרטון הועלה ונבדק.',queued:'הסרטון ממתין ל־worker המקומי.',processing:'MediaPipe מעבד את הסרטון…',complete:'הניתוח הסתיים בהצלחה.',failed:'עיבוד הסרטון נכשל.'};
  const ERRORS={invalid_request:'פרטי הקובץ אינם תקינים.',request_too_large:'הקובץ גדול מהמגבלה.',content_type_mismatch:'סוג הקובץ אינו תואם.',upload_size_mismatch:'גודל הקובץ אינו תואם.',checksum_mismatch:'בדיקת תקינות הקובץ נכשלה.',upload_metadata_mismatch:'אימות ההעלאה נכשל.',video_processing_error:'לא ניתן לעבד את הסרטון. בדקו שזהו קובץ וידאו תקין.',processing_timeout:'עיבוד הסרטון חרג ממגבלת הזמן.',required_file_missing:'קובץ הנדרש לעיבוד חסר.',internal_processing_error:'אירעה שגיאה פנימית בעיבוד.'};
  const el=id=>document.getElementById(id), input=el('video-file'), drop=el('drop-zone'), summary=el('file-summary'), start=el('start-upload'), status=el('status'), progress=el('progress'), bar=el('progress-bar'), results=el('results');
  let file=null,polling=false;
  const contentType=value=>TYPES[(value.name.split('.').pop()||'').toLowerCase()]||value.type;
  function setStatus(message,kind=''){status.textContent=message;status.dataset.kind=kind}
  function setPhase(phase){const current=ORDER.indexOf(phase);document.querySelectorAll('.step').forEach(step=>{const index=ORDER.indexOf(step.dataset.step);step.classList.toggle('done',phase==='complete'||index<current);step.classList.toggle('active',index===current&&phase!=='complete')})}
  function choose(value){const type=contentType(value);if(!Object.values(TYPES).includes(type))return setStatus('יש לבחור קובץ MP4, MOV או WebM.','error');if(!value.size||value.size>MAX_BYTES)return setStatus('גודל הסרטון חייב להיות בין 1 byte ל־250 MiB.','error');file=value;el('file-name').textContent=value.name;el('file-details').textContent=`${(value.size/1024/1024).toFixed(1)} MiB · ${type}`;summary.hidden=false;start.disabled=false;results.hidden=true;setStatus('הסרטון מוכן להעלאה.')}
  function clearFile(){file=null;input.value='';summary.hidden=true;start.disabled=true;setStatus('בחרו סרטון כדי להתחיל.')}
  async function jsonRequest(url,options={}){const response=await fetch(url,options);let body={};try{body=await response.json()}catch(_){}if(!response.ok)throw new Error(ERRORS[body.error]||`הבקשה נכשלה (${response.status}).`);return body}
  function upload(url,headers,value){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('PUT',url);xhr.timeout=30*60*1000;Object.entries(headers).forEach(([name,val])=>xhr.setRequestHeader(name,val));xhr.upload.onprogress=event=>{if(event.lengthComputable)bar.style.width=`${Math.round(event.loaded/event.total*100)}%`};xhr.onload=()=>{let body={};try{body=JSON.parse(xhr.responseText)}catch(_){}xhr.status>=200&&xhr.status<300?resolve(body):reject(new Error(ERRORS[body.error]||`ההעלאה נכשלה (${xhr.status}).`))};xhr.onerror=()=>reject(new Error('לא ניתן להתחבר לשרת המקומי.'));xhr.ontimeout=()=>reject(new Error('זמן ההעלאה הסתיים.'));xhr.send(value)})}
  function showResults(urls){const labels={dashboard_html:'פתיחת הדשבורד',annotated_video:'הורדת הסרטון המסומן',analysis_json:'הורדת נתוני הניתוח',dashboard_json:'הורדת נתוני הדשבורד'},list=el('result-list');list.replaceChildren();Object.entries(labels).forEach(([key,label])=>{if(!urls[key])return;const link=document.createElement('a');link.href=urls[key];link.textContent=label;link.target=key==='dashboard_html'?'_blank':'_self';if(key!=='dashboard_html')link.download='';list.append(link)});results.hidden=false;el('reset').hidden=false;results.scrollIntoView({behavior:'smooth',block:'nearest'})}
  async function poll(sessionId){if(polling)return;polling=true;try{while(true){const job=await jsonRequest(`/api/video-sessions/${sessionId}`);setPhase(job.status);setStatus(STATUS[job.status]||`מצב: ${job.status}`,job.status==='failed'?'error':job.status==='complete'?'success':'');if(job.status==='complete'){sessionStorage.removeItem('gymbromatics_session');showResults(job.result_urls);return}if(job.status==='failed'){sessionStorage.removeItem('gymbromatics_session');throw new Error(ERRORS[job.error_code]||'עיבוד הסרטון נכשל.')}await new Promise(resolve=>setTimeout(resolve,2000))}}finally{polling=false}}
  async function run(){if(!file)return;start.disabled=true;el('clear-file').disabled=true;progress.hidden=false;bar.style.width='0%';try{const created=await jsonRequest('/api/video-sessions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:file.name,content_type:contentType(file),size_bytes:file.size})});sessionStorage.setItem('gymbromatics_session',created.session_id);setPhase('created');setStatus(STATUS.created);const receipt=await upload(created.upload.url,created.upload.headers,file);bar.style.width='100%';setPhase('uploaded');setStatus(STATUS.uploaded);await jsonRequest(`/api/video-sessions/${created.session_id}/upload-complete`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({size_bytes:receipt.size_bytes,checksum_sha256:receipt.checksum_sha256})});await poll(created.session_id)}catch(error){setStatus(error.message||'אירעה שגיאה.','error');start.disabled=false;el('clear-file').disabled=false}}
  input.addEventListener('change',()=>input.files[0]&&choose(input.files[0]));el('clear-file').addEventListener('click',clearFile);start.addEventListener('click',run);['dragenter','dragover'].forEach(name=>drop.addEventListener(name,event=>{event.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(name=>drop.addEventListener(name,event=>{event.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',event=>event.dataTransfer.files[0]&&choose(event.dataTransfer.files[0]));el('reset').addEventListener('click',()=>location.reload());const active=sessionStorage.getItem('gymbromatics_session');if(active){setStatus('ממשיך לעקוב אחר העיבוד הקודם…');poll(active).catch(error=>setStatus(error.message,'error'))}
})();
